### ISSUE TITLE
The glb file size is bigger than the size of gltf file

### ISSUE THREAD

**Issue by sliencioGLL** [Geopipe/gltf2glb#1]
I had used this tool to transform .gltf file to .glb file. 

conmand line as:  python gltf2glb.py -e -c input_file

But I find the glb file size is bigger than the size of gltf file.

![image](https://cloud.githubusercontent.com/assets/11345076/23204082/1c8db774-f920-11e6-9d64-d649de4d8f83.png)

 I feel so confused. Is it right?

I had embedded resource(.bin .glsl .jpg) in .gltf file.

**Comment by KermMartian** [comment]
That doesn't seem right. Can you provide one of the sample GLTF files?

**Comment by sliencioGLL** [comment]
@KermMartian   I am sure that all external resources had embedded into the .gltf file.

I want to upload the gtlf file for you, but it can't support this file type. I had tried to compress and pack it into ZIP type, but also failed. 

Can you give me your email?  I will send you as quick as possible!

**Comment by KermMartian** [comment]
Please send along to my GitHub username (that I'm using now) at the domain cemetech.net.

**Comment by sliencioGLL** [comment]
@KermMartian I have sent to your email. Please check it. Thank u.

**Comment by KermMartian** [comment]
Hmmm, I'm afraid I didn't receive it. Would you be able to post it as a public link on your DropBox or a similar file-hosting service?

**Comment by sliencioGLL** [comment]
@KermMartian I had sent to your email ( KermMartian@cemetech.net)
Is this address right?

**Comment by KermMartian** [comment]
That's correct, but I'm afraid I didn't receive anything.

**Comment by sliencioGLL** [comment]
@KermMartian  I have sent test data url of DropBox  to your email, please check it! Thx

**Comment by KermMartian** [comment]
I received it; thanks! I'll let you know what I find.

**Comment by KermMartian** [comment]
I believe your textures were getting embedded. Please try again with the latest commit and let me know if you have success.

**Comment by KermMartian** [comment]
This tool no longer generates GLBs from GLTFs; closing.
