### ISSUE TITLE
b3dm

### ISSUE THREAD

**Issue by lty1024** [Geopipe/gltf2glb#2]
I tried to use it to transform gltf to b3dm, but failed. Some errors shown on the console.
![Uploading 捕获.JPG…]()
Is the order I typed right?
please tell me the right way to use the tool. Thank you !

**Comment by lty1024** [comment]
I filed to upload the jpg. So I paste the error line.
D:\课题\gltf2glb>python gltf2glb.py -b B3DM -o test.b3dm test.gltf
Traceback (most recent call last):
  File "gltf2glb.py", line 232, in <module>
    main()
  File "gltf2glb.py", line 220, in main
    with open(args.b3dm, 'r') as f:
IOError: [Errno 2] No such file or directory: 'B3DM'

**Comment by KermMartian** [comment]
The argument to -b is the path to the file containing the JSON batch table to embed in the b3dm file. If you don't have any batch data, use "" as the argument to -b. Hope this helps.

**Comment by lty1024** [comment]
wow! I succeed! Thank you very much!

**Comment by lty1024** [comment]
@KermMartian While I have another question. Does the tool support to batch multi gltf models into one b3dm file?

**Comment by KermMartian** [comment]
That would be the 'cmpt' output type.

**Comment by lty1024** [comment]
I use the 'packcmpt.py' to batch 5 gltfs into a file. The result I get is much smaller than the primary gltf data. Is it right?
![test](https://cloud.githubusercontent.com/assets/20310231/24230790/d62ad516-0fbb-11e7-8b32-d4856cb5499d.JPG)

**Comment by KermMartian** [comment]
No, this is definitely not correct; the cmpt should be roughly the sum of the sizes of the b3dms. What arguments did you give packcmpt.py?

**Comment by lty1024** [comment]
The order is “python packcmpt.py -o test.cmpt 1.b3dm 2.b3dm 3.b3dm 4.b3dm 5.b3dm”.
And I got the same result.
Did I give the wrong arguments?

**Comment by KermMartian** [comment]
Please try again with the latest commits and let me know if it works correctly for you.

**Comment by lty1024** [comment]
The latest commit is useful, and the result is right.

**Comment by KermMartian** [comment]
Great. In that case, closing this issue for now.
