### ISSUE TITLE
gltf2glb

### ISSUE THREAD

**Issue by pannous** [Geopipe/gltf2glb#23]
How does gltf2glb provide gltf2glb functionality?

"It has evolved to remove its first component (gltf2glb.py)"

You had one job! 

/entitled rant

**Comment by KermMartian** [comment]
Yeah, sorry about that, it basically no longer does what it says on the tin.

Since this tool was created, other tools have evolved to do the same thing, and better (i.e., most tooling that generates GLTF files now can just generate GLB instead as a first-class citizen).
